version: '3'
services:
  app:
    image: registry.khost.ch/visiflex_dev/app:latest
    container_name: app
    restart: unless-stopped
    env_file:
      - .app.env
      - .ldap.env
      - .mail.env
      - .imap.env
      - .db.env
    user: www-data
    working_dir: /var/www/app
    ports:
      - "80:80"
    volumes:
      - storagedata:/var/www/app/storage
    networks:
      - app-network
    depends_on:
      - db
  worker:
    image: registry.khost.ch/visiflex_dev/app:latest
    container_name: worker
    restart: unless-stopped
    env_file:
      - .app.env
      - .ldap.env
      - .mail.env
      - .imap.env
      - .db.env
    user: www-data
    entrypoint: /usr/local/bin/php /var/www/app/artisan queue:work
    working_dir: /var/www/app
    volumes:
      - storagedata:/var/www/app/storage
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: s3cr3tstring
#     SERVICE_TAGS: dev
#    SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  storagedata:
    driver: local
